CLEAR BREAKS;
CLEAR COLUMNS;

COLUMN SCN                      FORMAT A20            HEADING SCN;
COLUMN TRANID                 FORMAT A10            HEADING TRANID;
COLUMN ROLLBACK             FORMAT 99              HEADING RB;
COLUMN OPERATION_CODE FORMAT 9999999     HEADING OP_CODE;
COLUMN SQL_REDO             FORMAT A15           HEADING REDO WORD_WRAP;
COLUMN SQL_UNDO             FORMAT A15           HEADING UNDO WORD_WRAP;
COLUMN CSF                       FORMAT 999           HEADING CSF;
COLUMN STATUS                 FORMAT 9999          HEADING STAT;
COLUMN TIMESTAMP            FORMAT A17           HEADING TIMESTAMP;
COLUMN RBABLK                 FORMAT 999999999 HEADING RBABLK;
COLUMN RBABYTE               FORMAT 999999999 HEADING RBABYTE;
COLUMN RBASQN                FORMAT 999999999 HEADING RBASQN;

alter session set nls_timestamp_format = 'SYYYY-MM-DD-HH24-MI-SS.FF9';

SET ARRAYSIZE 100
SET PAGESIZE 9999;
SET LINESIZE 140;

BREAK ON RBABLK SKIP PAGE;

SELECT 
       OPERATION_CODE,
       SQL_REDO,
       SQL_UNDO,
       STATUS,
       RBABLK,
       RBABYTE,
       RBASQN,
       TO_CHAR(TIMESTAMP,'YY/MM/DD HH24:MI:SS') AS TIMESTAMP
FROM V$LOGMNR_CONTENTS;
