SELECT PLAN_NAME FROM DBA_SQL_PLAN_BASELINES WHERE SQL_HANDLE='SQL_6C0845687118FC3F';
PLAN_NAME
--------------------------------------------------------------------------------
SQL_PLAN_6s225d1sjjz1z193ccf8b
SQL_PLAN_6s225d1sjjz1z642e4a26
SQL_PLAN_6s225d1sjjz1z97bbe3d0

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY_SQL_PLAN_BASELINE(PLAN_NAME => 'SQL_PLAN_6S225D1SJJZ1Z193CCF8B', FORMAT => 'OUTLINE'));

/*+
BEGIN_OUTLINE_DATA
BATCH_TABLE_ACCESS_BY_ROWID(@"SEL$1" "TEST"@"SEL$1")
INDEX_RS_ASC(@"SEL$1" "TEST"@"SEL$1" ("TEST"."ID"))
OUTLINE_LEAF(@"SEL$1")
OPT_PARAM('_optimizer_use_feedback' 'false')
DB_VERSION('12.1.0.1')
OPTIMIZER_FEATURES_ENABLE('12.1.0.1')
IGNORE_OPTIM_EMBEDDED_HINTS
END_OUTLINE_DATA
*/

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY_SQL_PLAN_BASELINE(PLAN_NAME => 'SQL_PLAN_6S225D1SJJZ1Z642E4A26', FORMAT => 'OUTLINE'));

/*+
BEGIN_OUTLINE_DATA
INDEX_RS_ASC(@"SEL$1" "TEST"@"SEL$1" ("TEST"."ID"))
OUTLINE_LEAF(@"SEL$1")
RBO_OUTLINE
OPT_PARAM('_optimizer_use_feedback' 'false')
DB_VERSION('12.1.0.1')
OPTIMIZER_FEATURES_ENABLE('12.1.0.1')
IGNORE_OPTIM_EMBEDDED_HINTS
END_OUTLINE_DATA
*/

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY_SQL_PLAN_BASELINE(PLAN_NAME => 'SQL_PLAN_6S225D1SJJZ1Z97BBE3D0', FORMAT => 'OUTLINE'));

/*+
BEGIN_OUTLINE_DATA
FULL(@"SEL$1" "TEST"@"SEL$1")
OUTLINE_LEAF(@"SEL$1")
OPT_PARAM('_optimizer_use_feedback' 'false')
DB_VERSION('12.1.0.1')
OPTIMIZER_FEATURES_ENABLE('12.1.0.1')
IGNORE_OPTIM_EMBEDDED_HINTS
END_OUTLINE_DATA
*/
